version: '2.1'

services:
  eventum:
    image: eventum/eventum:3.8.0
    volumes:
      - ./config:/app/config
      - ./cache:/app/var/cache
      - ./log:/app/var/log
      - ./log/nginx:/var/log/nginx
      - ./log/fpm:/var/log/php/7.1
      - ./lock:/app/var/lock
      - ./session:/var/run/php/session
      - ./storage:/app/var/storage
    ports:
      - "8088:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  mysql:
    image: percona:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=eventum
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  mysql:
    labels:
      - "com.eventum.description=Eventum MySQL Database Volume"

# vim:ts=2:sw=2:et
