version: "2"

volumes:
  code-3.3.2:
  config:
  mysql:

services:
  code:
    image: eventum/code:3.3.2
    volumes:
      - code-3.3.2:/usr/src/eventum

  runtime:
    image: eventum/runtime:3.3.2
    volumes_from:
      - code
    volumes:
      - config:/usr/src/eventum/config
    links:
      - mysql

  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=eventum

  nginx:
    build: nginx
    ports:
      - "8088:80"
    links:
      - runtime:fpm
    volumes_from:
      - code

# vim:ts=2:sw=2:et
