version: '2.1'

services:
  eventum:
    build: .
    volumes:
      # share htdocs with nginx container
      - public:/app/htdocs

  mysql:
    image: percona:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=eventum

  nginx:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - public:/app/htdocs:ro

volumes:
  public:
  mysql:

# vim:ts=2:sw=2:et
