version: "3.4"

services:
  eventum:
    image: eventum/eventum:3.9.3
    volumes:
      - ./config:/app/config
      - ./var/cache:/app/var/cache
      - ./var/log:/app/var/log
      - ./var/log/nginx:/var/log/nginx
      - ./var/log/fpm:/var/log/php/7.2
      - ./var/lock:/app/var/lock
      - ./var/session:/app/var/session
      - ./var/storage:/app/var/storage
    environment:
      - APP_ENV=prod
    ports:
      - "8088:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  mysql:
    image: percona:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=eventum
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  mysql:
    labels:
      - "com.eventum.description=Eventum MySQL Database Volume"

# vim:ts=2:sw=2:et
