version: "2"

volumes:
  code-3.1.4:
  config:
  mysql:

services:
  eventum:
    image: eventum
    volumes:
      - code-3.1.4:/src/eventum
      - config:/src/eventum/config
    links:
      - mysql

  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=eventum

  nginx:
    build: nginx
    ports:
      - "8088:80"
    links:
      - eventum:fpm
    volumes:
      - code-3.1.4:/src/eventum:ro
      - config:/src/eventum/config:ro

# vim:ts=2:sw=2:et
