version: '2.1'

services:
  eventum:
    image: eventum/eventum:3.7.2
    ports:
      - "8088:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  mysql:
    image: percona:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=eventum
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  mysql:

# vim:ts=2:sw=2:et
