version: '2.1'

services:
  eventum:
    build: .
    volumes:
      - ./php.ini:/etc/php/7.1/php.ini
    ports:
      - "8088:80"

  mysql:
    image: percona:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=eventum

volumes:
  mysql:

# vim:ts=2:sw=2:et
