version: "2"

volumes:
  code-3.3.3:
  config:
  mysql:

services:
  eventum:
    image: eventum/eventum:3.3.3
    volumes:
      - code-3.3.3:/usr/src/eventum
      - config:/usr/src/eventum/config
    links:
      - mysql

  mysql:
    image: mysql:5.6
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=eventum

  nginx:
    build: nginx
    ports:
      - "8088:80"
    links:
      - eventum:fpm
    volumes:
      - code-3.3.3:/usr/src/eventum:ro

# vim:ts=2:sw=2:et
